name: Deploy CloudFormation

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - delete
      region:
        description: 'Region to deploy to'
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - us-east-2
          - us-west-2
          - eu-west-1
          - eu-west-2
          - eu-central-1
          - ap-southeast-1
          - ap-northeast-1
  pull_request: # deploy on PR merges to main
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.action == 'deploy' || github.event.inputs.action == 'delete'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        if: ${{ github.event.inputs.action == 'deploy' }}
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dls-test
          template: cloudformation/data-lake.yml
          no-fail-on-empty-changeset: "1"
      
      - name: Zip Lambda function
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
          cd ingestion_lambda
          zip -r ../lambda.zip . -x "*.git*" "*.DS_Store"

      - name: Upload Lambda zip to S3
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
          aws s3 cp lambda.zip s3://dls-component-name-dls-region/lambda.zip

      - name: Delete CloudFormation stack
        if: ${{ github.event.inputs.action == 'delete' }}
        run: |
          aws cloudformation delete-stack --stack-name dls-test
