name: Deploy CloudFormation - Frank's website

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: deploy or delete'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - delete
  pull_request: # deploy on PR merges to main
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.action == 'deploy' || github.event.inputs.action == 'delete'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        if: ${{ github.event.inputs.action == 'deploy' }}
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Frank's website
          template: website.yml
          no-fail-on-empty-changeset: "1"

      - name: Delete CloudFormation stack
        if: ${{ github.event.inputs.action == 'delete' }}
        run: |
          aws cloudformation delete-stack --stack-name Frank's website
